- hosts: webserver
  vars_files:
        - "/root/haproxyws_ansible/webvar.yml"
  tasks:
  - name: Installing httpd package
    package:
        name: httpd
        state: present

  - name: Copying Website Content 
    copy:
        src: "{{ webcontent }}"
        dest: "{{ webdir }}"

  - name: Configuring Firewall
    firewalld:
        port: "80/tcp"
        state: enabled
        permanent: yes
        immediate: yes

  - name: Starting httpd services
    service:
         name: httpd
         state: started

- hosts: haproxy_server
  vars_files:
         - "/root/haproxyws_ansible/haproxyvar.yml"
  tasks:
  - name: Installing haproxy package
    package:
        name: haproxy
        state: present

  - name: Configuring the configuration file
    template:
        src: "{{ cfgsrc }}"
        dest: "{{ cfgdest }}"

  - name: Configuring Firewall
    firewalld:
        port: "{{ haport }}/tcp"
        state: enabled
        permanent: yes
        immediate: yes

  - name: Starting haproxy services
    service:
        name: haproxy
        state: started
